name: gh-pages
on:
  push:
    branches: ['master']
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: Deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build/electrode-native-website
